"use client";

import Link from "next/link";
import { ArrowLeft, Bot, CheckCircle2, ExternalLink, FileSearch, Search, ShieldAlert, UserCheck } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { useWorkspace } from "@/components/workspace";
import { Button, Card, Field, Input, Notice, Select, Textarea } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import type { Issue, User } from "@/lib/types";

export default function IssueDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { project } = useWorkspace();
  const [issue, setIssue] = useState<Issue>(); const [members, setMembers] = useState<User[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [description, setDescription] = useState(""); const [measure, setMeasure] = useState(""); const [assignee, setAssignee] = useState(0); const [due, setDue] = useState(""); const [ignoreReason, setIgnoreReason] = useState("");
  const load = useCallback(() => api<Issue>(`/api/issues/${id}`).then((data) => { setIssue(data); setDescription((current) => current || data.description); setMeasure((current) => current || data.latest_rag_job?.result?.recommendations.join("\n") || ""); }).catch((e: ApiError) => setError(e.message)), [id]);
  useEffect(() => { void load(); void api<User[]>(`/api/projects/${project.id}/members`).then(setMembers); }, [load, project.id]);
  const analyze = async () => { setBusy(true); setError(""); try { await api(`/api/issues/${id}/rag-analyses`, { method: "POST" }); load(); } catch (e) { setError((e as ApiError).message); } finally { setBusy(false); } };
  const ignore = async () => { setBusy(true); try { await api(`/api/issues/${id}/ignore`, { method: "POST", body: JSON.stringify({ reason: ignoreReason }) }); load(); } catch (e) { setError((e as ApiError).message); } finally { setBusy(false); } };
  const createTask = async () => { if (!issue?.latest_rag_job) return; setBusy(true); try { const task = await api<{ id: number }>(`/api/issues/${id}/confirm-and-create-task`, { method: "POST", body: JSON.stringify({ final_description: description, rectification_measure: measure, assignee_id: assignee, due_at: new Date(due).toISOString(), rag_job_id: issue.latest_rag_job.id }) }); router.push(`/tasks/${task.id}?created=1`); } catch (e) { setError((e as ApiError).message); } finally { setBusy(false); } };
  if (!issue) return <div>{error ? <Notice tone="error">{error}</Notice> : <p className="py-12 text-center text-slate-500">正在读取问题证据…</p>}</div>;
  const job = issue.latest_rag_job;
  return <div className="mx-auto max-w-3xl"><Link href="/issues" className="mb-4 inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-site-700"><ArrowLeft size={17}/>返回问题列表</Link>{error && <div className="mb-4"><Notice tone="error">{error}</Notice></div>}
    <p className="text-xs font-bold tracking-widest text-site-600">ISSUE DECISION</p><h1 className="mt-1 break-words text-3xl font-black text-ink-900">{issue.description}</h1><p className="mt-1 text-sm text-slate-500">{issue.category} · {[issue.location.building, issue.location.floor, issue.location.zone].filter(Boolean).join(" · ")}</p>
    <Card className="mt-5 bg-ink-900 p-4 text-white"><div className="grid grid-cols-4">{[[ShieldAlert,"原始事实"],[FileSearch,"项目依据"],[Bot,"辅助建议"],[UserCheck,"人工决策"]].map(([Icon,label], index) => <div key={label as string} className="relative text-center">{index < 3 && <span className="absolute left-[65%] top-4 h-px w-[70%] bg-white/15"/>}<span className={`relative mx-auto grid size-8 place-items-center rounded-lg ${index === 0 || job ? "bg-site-600 text-white" : "bg-white/10 text-white/35"}`}><Icon size={16}/></span><span className="mt-2 block text-[10px] font-bold sm:text-xs">{label as string}</span></div>)}</div></Card>
    <Card className="mt-4 border-l-4 border-l-site-600"><h2 className="flex items-center gap-2 font-bold"><ShieldAlert size={18}/>原始现场事实</h2><p className="mt-2 text-xs text-slate-500">问题描述和证据在人工确认时冻结，不随后续建议修改。</p>{issue.evidence.length ? <div className="mt-3 space-y-2">{issue.evidence.map((e, i) => <div key={i} className="rounded-xl bg-ink-50 p-3 text-sm"><p>{e.quote || e.description}</p><p className="mt-1 text-xs text-slate-500">证据类型：{e.evidence_type}</p></div>)}</div> : <p className="mt-3 text-sm text-slate-500">已由人员确认，但未提供可显示的问题级字段引用</p>}<Link href={`/records/${issue.record_id}`} className="mt-3 inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-site-700"><ExternalLink size={15}/>查看来源现场记录</Link></Card>
    {!job && <Card className="mt-4 text-center"><Search className="mx-auto text-site-700"/><p className="mt-2 font-bold">查询项目知识库依据</p><p className="mt-1 text-sm text-slate-500">无合格命中文段时不会调用模型。</p><Button className="mt-4 w-full" onClick={analyze} disabled={busy}>开始查询</Button></Card>}
    {job && <Card className="mt-4"><h2 className="flex items-center gap-2 font-bold"><Bot size={18}/>检索与辅助建议</h2><p className="mt-2 text-xs text-slate-500">{job.provider} / {job.model} · {job.status}</p>{job.error_message && <div className="mt-3"><Notice tone={job.status === "NO_EVIDENCE" ? "info" : "error"}>{job.error_message}</Notice></div>}{job.result && <><div className="mt-4 rounded-xl bg-blue-50 p-3 text-sm"><strong>疑似影响（辅助判断）</strong><p className="mt-1">{job.result.suspected_impact}</p></div><div className="mt-4"><h3 className="font-semibold">建议</h3><ul className="mt-2 space-y-2 text-sm">{job.result.recommendations.map((item, i) => <li key={i}>• {item}</li>)}</ul></div><div className="mt-4 space-y-3"><h3 className="font-semibold">逐条引用</h3>{job.result.citations.map((citation) => <div key={`${citation.chunk_id}-${citation.excerpt}`} className="rounded-xl border border-slate-200 p-3"><p className="text-sm">“{citation.excerpt}”</p><p className="mt-2 text-xs text-slate-500">{citation.document_title} · {citation.locator}</p>{citation.is_demo && <p className="mt-1 text-xs font-semibold text-amber-800">非正式演示材料，不是正式规范</p>}</div>)}</div>{job.result.warnings.map((warning, i) => <p key={i} className="mt-2 text-xs text-amber-800">⚠ {warning}</p>)}</>} {(["FAILED", "NO_EVIDENCE"].includes(job.status)) && <Button className="mt-4" variant="secondary" onClick={analyze}>重新查询</Button>}</Card>}
    {job?.status === "SUCCEEDED" && !issue.task_id && issue.status !== "IGNORED" && <Card className="mt-4 space-y-4"><h2 className="flex items-center gap-2 font-bold"><CheckCircle2 size={18}/>人工确认并创建整改任务</h2><Notice>以下字段是新的人工输入，不会写回或冒充现场原始证据。</Notice><Field label="最终问题描述"><Textarea value={description} onChange={(e) => setDescription(e.target.value)}/></Field><Field label="整改措施"><Textarea value={measure} onChange={(e) => setMeasure(e.target.value)}/></Field><Field label="责任人"><Select value={assignee} onChange={(e) => setAssignee(Number(e.target.value))}><option value="0">请选择项目成员</option>{members.map((m) => <option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</Select></Field><Field label="截止时间"><Input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)}/></Field><Button className="w-full" disabled={busy || !description || !measure || !assignee || !due} onClick={createTask}>确认并建单</Button></Card>}
    {!issue.task_id && issue.status !== "IGNORED" && <Card className="mt-4"><h2 className="font-bold">忽略该问题</h2><Field label="忽略原因（必填）"><Textarea className="mt-3" value={ignoreReason} onChange={(e) => setIgnoreReason(e.target.value)}/></Field><Button className="mt-3" variant="danger" disabled={busy || !ignoreReason.trim()} onClick={ignore}>记录原因并忽略</Button></Card>}
    {issue.task_id && <Button asChild className="mt-4 w-full"><Link href={`/tasks/${issue.task_id}`}>查看整改任务 #{issue.task_id}</Link></Button>}
  </div>;
}
