"use client";

import Link from "next/link";
import { ArrowRight, BookOpenText, Camera, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, FileCheck2, Fingerprint, ListChecks, MapPin, Mic2, Plus, RefreshCw, ShieldCheck, Sparkles, UserRound, Workflow } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge, Button, Card, Notice } from "@/components/ui";
import { useWorkspace } from "@/components/workspace";
import { api, ApiError } from "@/lib/api";
import type { Dashboard, TaskReminders } from "@/lib/types";
import { formatDate } from "@/lib/utils";

export default function HomePage() {
  const { user, project } = useWorkspace();
  const [data, setData] = useState<Dashboard>();
  const [reminders, setReminders] = useState<TaskReminders>();
  const [error, setError] = useState("");
  const load = () => {
    setError("");
    Promise.all([api<Dashboard>(`/api/projects/${project.id}/dashboard`), api<TaskReminders>(`/api/projects/${project.id}/task-reminders`)])
      .then(([dashboard, reminderData]) => { setData(dashboard); setReminders(reminderData); })
      .catch((e: ApiError) => setError(e.message));
  };
  useEffect(load, [project.id]);

  return <div className="space-y-5">
    <section className="blueprint-grid relative overflow-hidden rounded-[1.75rem] bg-ink-900 px-5 py-6 text-white shadow-lift md:px-8 md:py-7">
      <div className="absolute -right-20 -top-32 size-80 rounded-full border border-gold-300/20"/><div className="absolute right-16 top-10 size-44 rounded-full border border-white/[.07]"/>
      <div className="relative grid items-center gap-7 lg:grid-cols-[1.25fr_.75fr]">
        <div><div className="mb-4 flex flex-wrap items-center gap-2"><Badge tone="gold">{project.status}</Badge><span className="text-xs text-white/45">{project.address} · {user.name} {user.role}</span></div><p className="mb-2 flex items-center gap-2 text-xs font-bold tracking-[.18em] text-gold-300"><Sparkles size={15}/>今日现场工作</p><h1 className="text-3xl font-black leading-tight tracking-tight md:text-4xl xl:text-[2.75rem]">现场说一次，<span className="text-site-500">资料自动成</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55 md:text-base">把照片、语音、人员、时间和位置沉淀为可追溯事实，让问题从发现一直跟到闭环。</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/records/new"><Plus size={20}/>新建现场记录</Link></Button><Button asChild size="lg" variant="secondary" className="border-white/15 bg-white/[.07] text-white hover:border-white/25 hover:bg-white/10"><Link href="/records/new?mode=voice"><Mic2 size={19}/>语音记录</Link></Button></div></div>
        <div className="grid grid-cols-2 gap-3"><QuickAction href="/records/new" icon={Camera} title="拍照填写" text="原始事实即时留存"/><QuickAction href="/records/new?mode=voice" icon={Mic2} title="按住说话" text="边巡场边完成记录"/><QuickAction href="/logs" icon={BookOpenText} title="今日日志" text="现场事实自动复用"/><QuickAction href="/tasks" icon={ClipboardCheck} title="整改中心" text="责任到人持续跟进"/></div>
      </div>
    </section>

    {error && <Notice tone="error"><span>{error}</span><button className="ml-2 underline" onClick={load}><RefreshCw className="inline" size={14}/>重试</button></Notice>}
    {!data && !error ? <DashboardSkeleton/> : data && <>
      <section aria-label="项目关键指标" className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5"><Metric icon={Camera} value={data.today_records} label="今日现场记录" caption="按项目本地日统计"/><Metric icon={Fingerprint} value={data.confirmed_events} label="已确认现场事实" caption="人工核对留痕"/><Metric icon={ShieldCheck} value={data.pending_issues} label="问题待确认" caption="等待专业判断" tone="warning"/><Metric icon={Clock3} value={data.waiting_review_rectifications} label="整改待复核" caption="责任人不可自审" tone="brand"/><Metric icon={CheckCircle2} value={data.closed_rectifications_today} label="今日完成闭环" caption="整改与复核完成" tone="success" className="col-span-2 sm:col-span-1"/></section>
      <section className="grid min-w-0 gap-5 xl:grid-cols-[1.25fr_.75fr]">
        <Card className="competition-card min-w-0 overflow-hidden p-0"><div className="flex items-center justify-between border-b border-black/5 px-5 py-4"><div className="min-w-0"><p className="text-xs font-bold tracking-widest text-site-600">EVIDENCE FIRST</p><h2 className="mt-1 text-lg font-black text-ink-900">一条现场事实，驱动完整工作闭环</h2></div><Workflow className="shrink-0 text-site-600"/></div><div className="flex w-full overflow-x-auto p-4 md:p-5">{[[Camera,"现场证据","照片·语音"],[Fingerprint,"事实确认","AI提取·人工核对"],[FileCheck2,"日志复用","施工·安全日志"],[ListChecks,"整改建单","责任人·截止时间"],[CheckCircle2,"复核闭环","照片·审计记录"]].map(([Icon,label,sub], index) => <div key={label as string} className="relative min-w-28 flex-1 px-1 text-center">{index < 4 && <span className="absolute left-[62%] top-5 h-px w-[76%] bg-gradient-to-r from-site-300 to-gold-300"/>}<span className="relative mx-auto grid size-10 place-items-center rounded-xl bg-site-50 text-site-700 ring-4 ring-white"><Icon size={19}/></span><strong className="mt-3 block text-xs text-ink-900 md:text-sm">{label as string}</strong><span className="mt-1 block text-[10px] text-slate-400 md:text-xs">{sub as string}</span></div>)}</div></Card>
        <Card className="competition-card border-gold-300/45 bg-gradient-to-br from-[#fffaf0] to-white"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-widest text-gold-700">TODAY</p><h2 className="mt-1 text-lg font-black text-ink-900">整改提醒</h2></div><Badge tone={reminders && reminders.counts.overdue > 0 ? "warning" : "success"}>{reminders && reminders.counts.overdue > 0 ? "需要关注" : "进度正常"}</Badge></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Reminder value={reminders?.counts.yesterday_unclosed ?? 0} label="昨日未闭环"/><Reminder value={reminders?.counts.overdue ?? 0} label="已逾期"/><Reminder value={reminders?.counts.waiting_review ?? 0} label="待复核"/></div><Button asChild variant="secondary" className="mt-4 w-full bg-white"><Link href="/tasks">进入整改中心<ArrowRight size={16}/></Link></Button></Card>
      </section>
      <section className="grid min-w-0 gap-5 lg:grid-cols-2"><div className="min-w-0"><SectionTitle title="最近现场记录" href="/records"/><div className="min-w-0 space-y-3">{data.recent_records.slice(0, 3).map((record) => <Link key={record.id} href={`/records/${record.id}`} className="block min-w-0"><Card className="competition-card flex min-w-0 items-center gap-4 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-site-50 text-site-700"><Camera size={20}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><Badge tone="brand">{record.category}</Badge><time className="text-[11px] text-slate-400">{formatDate(record.occurred_at)}</time></div><p className="mt-2 truncate text-sm font-semibold text-ink-900">{record.description}</p><p className="mt-1 truncate text-xs text-slate-400"><MapPin className="mr-1 inline" size={12}/>{record.location.building} · {record.location.floor} · {record.location.zone}</p></div><ChevronRight className="shrink-0 text-slate-300" size={18}/></Card></Link>)}{!data.recent_records.length && <Empty text="今天还没有现场记录"/>}</div></div><div className="min-w-0"><SectionTitle title="即将到期" href="/tasks"/><div className="min-w-0 space-y-3">{data.upcoming_tasks.slice(0, 3).map((task) => <Link key={task.id} href={`/tasks/${task.id}`} className="block min-w-0"><Card className="competition-card flex min-w-0 items-center gap-4 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-gold-100 text-gold-700"><ListChecks size={20}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><Badge tone={task.kind === "RECTIFICATION" ? "warning" : "neutral"}>{task.kind === "RECTIFICATION" ? "整改任务" : "普通待办"}</Badge><span className="text-[11px] font-bold text-site-600">{formatDate(task.due_at)}</span></div><p className="mt-2 truncate text-sm font-semibold text-ink-900">{task.title}</p><p className="mt-1 truncate text-xs text-slate-400"><UserRound className="mr-1 inline" size={12}/>{task.assignee.name} · {task.assignee.role}</p></div><ChevronRight className="shrink-0 text-slate-300" size={18}/></Card></Link>)}{!data.upcoming_tasks.length && <Empty text="没有即将到期的待办"/>}</div></div></section>
    </>}
  </div>;
}

function QuickAction({ href, icon: Icon, title, text }: { href: string; icon: typeof Camera; title: string; text: string }) { return <Link href={href} className="group rounded-2xl border border-white/10 bg-white/[.055] p-3 transition hover:border-gold-300/30 hover:bg-white/[.09]"><Icon className="text-gold-300 transition group-hover:scale-105" size={20}/><strong className="mt-3 block text-sm">{title}</strong><span className="mt-1 block text-[11px] text-white/40">{text}</span></Link>; }
function Reminder({ value, label }: { value: number; label: string }) { return <div className="rounded-xl border border-gold-300/25 bg-white p-2.5"><strong className="block text-2xl text-ink-900">{value}</strong><span className="block text-[11px] text-slate-500">{label}</span></div>; }
function Metric({ icon: Icon, value, label, caption, tone = "neutral", className = "" }: { icon: typeof Camera; value: number; label: string; caption: string; tone?: "neutral" | "brand" | "warning" | "success"; className?: string }) { const styles = { neutral: "bg-ink-50 text-ink-700", brand: "bg-site-50 text-site-700", warning: "bg-amber-50 text-amber-700", success: "bg-emerald-50 text-emerald-700" }; return <Card className={`competition-card min-w-0 p-4 ${className}`}><div className="flex items-start justify-between gap-2"><span className={`grid size-9 place-items-center rounded-xl ${styles[tone]}`}><Icon size={18}/></span><strong className="text-3xl font-black tracking-tight text-ink-900">{value}</strong></div><p className="mt-4 truncate text-sm font-bold text-ink-800">{label}</p><p className="mt-1 truncate text-[11px] text-slate-400">{caption}</p></Card>; }
function SectionTitle({ title, href }: { title: string; href: string }) { return <div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-ink-900">{title}</h2><Link href={href} className="flex min-h-10 items-center gap-1 text-sm font-bold text-site-600">查看全部<ArrowRight size={15}/></Link></div>; }
function Empty({ text }: { text: string }) { return <Card className="py-8 text-center text-sm text-slate-400">{text}</Card>; }
function DashboardSkeleton() { return <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{Array.from({ length: 5 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-[1.25rem] bg-white/70"/>)}</div>; }
