"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { Camera, CheckCircle2, Crosshair, ImagePlus, Loader2, MapPin, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useWorkspace } from "@/components/workspace";
import { Button, Card, Field, Input, Notice, Select, Textarea } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import type { Location, RecordItem } from "@/lib/types";

const categories = ["施工进度", "安全巡查", "质量检查", "材料进场", "人员作业", "其他"] as const;
const schema = z.object({ category: z.enum(categories), description: z.string().min(1, "请输入现场描述").max(5000), building: z.string().min(1, "请选择楼栋"), floor: z.string().min(1, "请选择楼层"), location_id: z.number().positive("请选择区域") });
type Values = z.infer<typeof schema>;
type GPS = { status: "not_requested" | "loading" | "success" | "unsupported" | "denied" | "timeout" | "failed"; latitude?: number; longitude?: number; accuracy?: number; capturedAt?: string };

export default function NewRecordPage() {
  const { user, project } = useWorkspace(); const router = useRouter(); const [locations, setLocations] = useState<Location[]>([]); const [files, setFiles] = useState<File[]>([]); const [fileError, setFileError] = useState(""); const [serverError, setServerError] = useState(""); const [uploading, setUploading] = useState(false); const [gps, setGps] = useState<GPS>({ status: "not_requested" });
  const { register, handleSubmit, watch, setValue, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { category: "安全巡查", building: "", floor: "" } });
  useEffect(() => { api<Location[]>(`/api/projects/${project.id}/locations`).then(setLocations).catch((e: ApiError) => setServerError(e.message)); }, [project.id]);
  const building = watch("building"), floor = watch("floor");
  const buildings = useMemo(() => [...new Set(locations.map((item) => item.building))], [locations]);
  const floors = useMemo(() => [...new Set(locations.filter((item) => item.building === building).map((item) => item.floor))], [locations, building]);
  const zones = locations.filter((item) => item.building === building && item.floor === floor);
  const previews = useMemo(() => files.map((file) => ({ file, url: URL.createObjectURL(file) })), [files]);
  useEffect(() => () => previews.forEach((item) => URL.revokeObjectURL(item.url)), [previews]);
  const chooseFiles = (incoming: FileList | null) => { if (!incoming) return; const next = [...files, ...Array.from(incoming)]; if (next.length > 9) { setFileError("每条记录最多上传 9 张照片"); return; } const bad = next.find((file) => file.size > 10 * 1024 * 1024 || !["image/jpeg","image/png","image/webp"].includes(file.type)); if (bad) { setFileError("仅支持 10MB 以内的 JPEG、PNG、WebP 图片"); return; } setFileError(""); setFiles(next); };
  const locate = () => { if (!("geolocation" in navigator)) { setGps({ status: "unsupported" }); return; } setGps({ status: "loading" }); navigator.geolocation.getCurrentPosition((position) => setGps({ status: "success", latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, capturedAt: new Date(position.timestamp).toISOString() }), (error) => setGps({ status: error.code === 1 ? "denied" : error.code === 3 ? "timeout" : "failed" }), { enableHighAccuracy: true, timeout: 10_000, maximumAge: 0 }); };
  const submit = async (values: Values) => { setServerError(""); try { const record = await api<RecordItem>("/api/records", { method: "POST", body: JSON.stringify({ project_id: project.id, category: values.category, description: values.description, occurred_at: new Date().toISOString(), location_id: values.location_id, gps_status: gps.status === "loading" ? "failed" : gps.status, latitude: gps.status === "success" ? gps.latitude : null, longitude: gps.status === "success" ? gps.longitude : null, gps_accuracy: gps.status === "success" ? gps.accuracy : null, gps_captured_at: gps.status === "success" ? gps.capturedAt : null }) }); if (files.length) { setUploading(true); const form = new FormData(); files.forEach((file) => form.append("files", file)); try { await api(`/api/records/${record.id}/photos`, { method: "POST", body: form }); } catch (error) { setUploading(false); setServerError(`记录已保存，但照片上传失败：${(error as ApiError).message}。可进入记录详情重新处理。`); return; } } router.push(`/records/${record.id}?created=1`); } catch (error) { setServerError((error as ApiError).message); } finally { setUploading(false); } };
  return <div className="mx-auto max-w-2xl"><div className="mb-5"><h1 className="text-2xl font-bold">新建现场记录</h1><p className="mt-1 text-sm text-slate-600">记录原始事实，照片与位置将一并留存</p></div>
    <form className="space-y-4" onSubmit={handleSubmit(submit)}>
      {serverError && <Notice tone="error">{serverError}</Notice>}
      <Card className="space-y-4"><h2 className="font-bold">现场信息</h2><Field label="记录类别" error={errors.category?.message}><Select {...register("category")}>{categories.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="现场描述" error={errors.description?.message}><Textarea placeholder="请如实描述现场看到的情况，不会自动改写" {...register("description")}/></Field><div className="grid grid-cols-2 gap-3"><Field label="记录时间"><Input value={new Date().toLocaleString("zh-CN")} readOnly/></Field><Field label="记录人"><Input value={`${user.name} · ${user.role}`} readOnly/></Field></div><Field label="所属项目"><Input value={project.name} readOnly/></Field></Card>
      <Card><div className="flex items-center justify-between"><div><h2 className="font-bold">GPS 定位</h2><p className="mt-1 text-xs text-slate-500">仅保存坐标，不判断楼栋或楼层</p></div><Button type="button" variant="secondary" onClick={locate} disabled={gps.status === "loading"}>{gps.status === "loading" ? <Loader2 className="animate-spin" size={17}/> : <Crosshair size={17}/>}获取当前位置</Button></div><GpsStatus gps={gps}/></Card>
      <Card className="space-y-4"><h2 className="font-bold">施工位置</h2><div className="grid gap-3 sm:grid-cols-3"><Field label="楼栋" error={errors.building?.message}><Select {...register("building")} onChange={(e) => { setValue("building", e.target.value, { shouldValidate: true }); setValue("floor", ""); setValue("location_id", 0); }}><option value="">请选择</option>{buildings.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="楼层" error={errors.floor?.message}><Select {...register("floor")} disabled={!building} onChange={(e) => { setValue("floor", e.target.value, { shouldValidate: true }); setValue("location_id", 0); }}><option value="">请选择</option>{floors.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="区域" error={errors.location_id?.message}><Select {...register("location_id", { valueAsNumber: true })} disabled={!floor}><option value="0">请选择</option>{zones.map((item) => <option key={item.id} value={item.id}>{item.zone}</option>)}</Select></Field></div></Card>
      <Card><div className="flex items-center justify-between"><div><h2 className="font-bold">现场照片</h2><p className="mt-1 text-xs text-slate-500">最多 9 张，单张不超过 10MB</p></div><span className="text-sm font-semibold text-site-700">{files.length}/9</span></div><label className="mt-4 flex min-h-24 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 text-slate-600 hover:border-site-500"><ImagePlus size={25}/><span className="mt-2 text-sm font-semibold">拍照或从相册选择</span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple onChange={(e) => { chooseFiles(e.target.files); e.target.value = ""; }}/></label>{fileError && <p className="mt-2 text-sm text-red-600">{fileError}</p>}<div className="mt-4 grid grid-cols-3 gap-2">{previews.map(({ file, url }, index) => <div key={`${file.name}-${index}`} className="relative aspect-square overflow-hidden rounded-xl bg-slate-100"><img src={url} alt={`待上传照片 ${index + 1}`} className="size-full object-cover"/><button type="button" aria-label={`删除照片 ${index + 1}`} onClick={() => setFiles(files.filter((_, i) => i !== index))} className="absolute right-1 top-1 grid size-9 place-items-center rounded-full bg-black/65 text-white"><Trash2 size={16}/></button></div>)}</div></Card>
      <Button className="w-full" size="lg" disabled={isSubmitting || uploading}>{uploading ? <><Loader2 className="animate-spin"/>正在上传照片…</> : isSubmitting ? "正在保存…" : <><Camera/>保存现场记录</>}</Button>
    </form>
  </div>;
}
function GpsStatus({ gps }: { gps: GPS }) { const map = { not_requested: ["尚未获取定位，仍可保存记录", "info"], loading: ["正在请求定位权限…", "info"], success: [`定位成功：${gps.latitude?.toFixed(6)}, ${gps.longitude?.toFixed(6)}（精度 ±${Math.round(gps.accuracy ?? 0)}m）`, "success"], unsupported: ["当前浏览器不支持定位，将保存为未获取定位", "error"], denied: ["定位权限已被拒绝，将保存为未获取定位", "error"], timeout: ["定位请求超时，将保存为未获取定位", "error"], failed: ["定位失败，将保存为未获取定位", "error"] } as const; const [text, tone] = map[gps.status]; return <div className="mt-4"><Notice tone={tone}><span className="flex items-center gap-2">{gps.status === "success" ? <CheckCircle2 size={17}/> : <MapPin size={17}/>} {text}</span></Notice></div>; }
