"use client";

import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, Loader2, Plus, RefreshCw, Save, Sparkles, Trash2 } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { useWorkspace } from "@/components/workspace";
import { Button, Card, Field, Input, Notice, Select, Textarea } from "@/components/ui";
import { api, ApiError, photoUrl } from "@/lib/api";
import type { EventDraft, EventIssue, EventPayload, Location, TranscriptionJob, User } from "@/lib/types";
import { localDateTime } from "@/lib/utils";

type TaskChoice = { create_task: boolean; title: string; assignee_id: number; due_at: string };
const categories = ["施工进度", "安全巡查", "质量检查", "材料进场", "人员作业", "其他"];

export default function VoiceReviewPage() {
  const { jobId } = useParams<{ jobId: string }>(); const { project } = useWorkspace(); const router = useRouter();
  const [job, setJob] = useState<TranscriptionJob>(); const [draft, setDraft] = useState<EventDraft>(); const [payload, setPayload] = useState<EventPayload>();
  const [transcript, setTranscript] = useState(""); const [locations, setLocations] = useState<Location[]>([]); const [members, setMembers] = useState<User[]>([]);
  const [category, setCategory] = useState("其他"); const [description, setDescription] = useState(""); const [building, setBuilding] = useState(""); const [floor, setFloor] = useState(""); const [locationId, setLocationId] = useState(0);
  const [choices, setChoices] = useState<Record<number, TaskChoice>>({}); const [evidenceJson, setEvidenceJson] = useState("{}"); const [error, setError] = useState(""); const [busy, setBusy] = useState("");

  useEffect(() => { Promise.all([api<Location[]>(`/api/projects/${project.id}/locations`), api<User[]>(`/api/projects/${project.id}/members`)]).then(([placeData, memberData]) => { setLocations(placeData); setMembers(memberData); }).catch((reason: ApiError) => setError(reason.message)); }, [project.id]);
  useEffect(() => {
    let active = true; let timer: ReturnType<typeof setTimeout>;
    const poll = async () => { try { const value = await api<TranscriptionJob>(`/api/transcription-jobs/${jobId}`); if (!active) return; setJob(value); if (value.status === "SUCCEEDED") { setTranscript((current) => current || value.edited_transcript || value.raw_transcript || ""); setDescription((current) => current || value.edited_transcript || value.raw_transcript || ""); return; } if (value.status === "FAILED") return; timer = setTimeout(poll, 1200); } catch (reason) { if (active) setError((reason as ApiError).message); } };
    poll(); return () => { active = false; clearTimeout(timer); };
  }, [jobId]);

  const buildings = useMemo(() => [...new Set(locations.map((item) => item.building))], [locations]);
  const floors = useMemo(() => [...new Set(locations.filter((item) => item.building === building).map((item) => item.floor))], [locations, building]);
  const zones = locations.filter((item) => item.building === building && item.floor === floor);
  const saveTranscript = async () => { if (!transcript.trim()) throw new ApiError("修订文本不能为空", 422); const updated = await api<TranscriptionJob>(`/api/transcription-jobs/${jobId}/transcript`, { method: "PATCH", body: JSON.stringify({ edited_transcript: transcript }) }); setJob(updated); return updated; };
  const generate = async () => { setBusy("generate"); setError(""); try { await saveTranscript(); setDescription(transcript); const value = await api<EventDraft>(`/api/transcription-jobs/${jobId}/event-drafts`, { method: "POST" }); setDraft(value); const next = value.user_corrected_payload ?? value.system_resolved_payload ?? value.raw_payload; if (next) { setPayload(next); setEvidenceJson(JSON.stringify(next.field_evidence, null, 2)); setCategory(({ construction_progress: "施工进度", safety_inspection: "安全巡查", quality_inspection: "质量检查", general: "其他" } as const)[next.event_type]); } else setError(value.safe_error_message || "草稿生成失败，请重试"); } catch (reason) { setError((reason as ApiError).message); } finally { setBusy(""); } };
  const retry = async () => { setBusy("retry"); setError(""); try { const value = await api<TranscriptionJob>(`/api/transcription-jobs/${jobId}/retry`, { method: "POST" }); setJob(value); window.location.reload(); } catch (reason) { setError((reason as ApiError).message); setBusy(""); } };
  const updateIssue = (index: number, changes: Partial<EventIssue>) => setPayload((current) => current ? { ...current, issues: current.issues.map((issue, itemIndex) => itemIndex === index ? { ...issue, ...changes } : issue) } : current);
  const saveDraft = async (next: EventPayload) => { if (!draft) return; const value = await api<EventDraft>(`/api/event-drafts/${draft.id}`, { method: "PATCH", body: JSON.stringify({ payload: next }) }); setDraft(value); };
  const confirm = async () => {
    if (!draft || !payload || !locationId || !description.trim()) { setError("请补齐现场描述和施工位置"); return; }
    setBusy("confirm"); setError("");
    try {
      const fieldEvidence = JSON.parse(evidenceJson) as EventPayload["field_evidence"];
      const corrected = { ...payload, field_evidence: fieldEvidence };
      await saveDraft(corrected);
      const selected = corrected.issues.flatMap((_, index) => { const choice = choices[index]; return choice?.create_task ? [{ issue_index: index, create_task: true, assignee_id: choice.assignee_id || null, due_at: choice.due_at ? new Date(choice.due_at).toISOString() : null, title: choice.title || null }] : []; });
      const result = await api<{ record: { id: number } }>(`/api/event-drafts/${draft.id}/confirm`, { method: "POST", body: JSON.stringify({ payload: corrected, record: { category, description, occurred_at: job?.created_at ?? new Date().toISOString(), location_id: locationId, gps_status: "not_requested", latitude: null, longitude: null, gps_accuracy: null, gps_captured_at: null }, issues: selected }) });
      router.push(`/records/${result.record.id}?created=1`);
    } catch (reason) { setError(reason instanceof SyntaxError ? "字段证据 JSON 格式无效" : (reason as ApiError).message); setBusy(""); }
  };

  if (!job) return <div className="py-12 text-center text-slate-500">正在读取转写任务…</div>;
  return <div className="mx-auto max-w-3xl"><Link href="/records/new" className="mb-4 inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-site-700"><ArrowLeft size={17}/>返回新建记录</Link>
    <div className="mb-5"><h1 className="text-2xl font-bold">核对语音记录</h1><p className="mt-1 text-sm text-slate-600">原始证据永久分开保存；只有最终确认才创建正式记录</p></div>
    {error && <div className="mb-4"><Notice tone="error">{error}</Notice></div>}
    <Card className="mb-4"><h2 className="font-bold">1. 原始录音</h2>{job.original_audio ? <audio className="mt-3 w-full" controls src={photoUrl(job.original_audio.content_url)}/> : <Notice tone="error">原始录音不可用</Notice>}<p className="mt-2 text-xs text-slate-500">原始文件不会被标准化文件或后续编辑覆盖</p></Card>
    {job.status === "FAILED" ? <Card className="mb-4 border-red-200"><Notice tone="error"><span className="flex items-center gap-2"><AlertTriangle size={17}/>{job.safe_error_message || "转写失败"}（{job.error_code}）</span></Notice><Button className="mt-3 w-full" onClick={retry} disabled={busy === "retry"}><RefreshCw size={17}/>重试转写</Button></Card> : job.status !== "SUCCEEDED" ? <Card className="mb-4 py-8 text-center"><Loader2 className="mx-auto animate-spin text-site-700"/><p className="mt-3 font-semibold">{job.status === "QUEUED" ? "等待处理…" : "正在标准化并转写…"}</p><p className="mt-1 text-xs text-slate-500">页面会自动更新，终态后停止轮询</p></Card> : <>
      <Card className="mb-4 space-y-4"><h2 className="font-bold">2. 核对转写</h2><Field label="ASR 原始文本"><Textarea value={job.raw_transcript ?? ""} readOnly className="bg-slate-50"/></Field><Field label="用户修订文本"><Textarea aria-label="用户修订文本" value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder="请逐字核对，可修改识别错误"/></Field><p className="text-xs text-slate-500">保存修订不会覆盖 ASR 原始文本；抽取优先使用修订文本。</p><Button variant="secondary" onClick={() => saveTranscript().catch((reason: ApiError) => setError(reason.message))}><Save size={17}/>保存修订文本</Button></Card>
      <Button size="lg" className="mb-4 w-full" onClick={generate} disabled={busy === "generate"}>{busy === "generate" ? <><Loader2 className="animate-spin"/>正在生成草稿…</> : <><Sparkles/> {draft ? "重新提取 Event 草稿" : "生成 Event 草稿"}</>}</Button>
    </>}
    {payload && draft && <>
      <Card className="mb-4 space-y-4"><div className="flex items-center gap-2"><CheckCircle2 className="text-site-700"/><h2 className="font-bold">3. 修改结构化 Event</h2></div>
        <Field label="Event 类型"><Select value={payload.event_type} onChange={(event) => setPayload({ ...payload, event_type: event.target.value as EventPayload["event_type"] })}><option value="construction_progress">施工进度</option><option value="safety_inspection">安全巡查</option><option value="quality_inspection">质量检查</option><option value="general">一般记录</option></Select></Field>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="施工活动"><Input value={payload.construction.activity ?? ""} onChange={(event) => setPayload({ ...payload, construction: { ...payload.construction, activity: event.target.value || undefined } })}/></Field><Field label="进度百分比"><Input type="number" min="0" max="100" value={payload.construction.progress_percent ?? ""} onChange={(event) => setPayload({ ...payload, construction: { ...payload.construction, progress_percent: event.target.value ? Number(event.target.value) : undefined } })}/></Field><Field label="班组"><Input value={payload.construction.crew ?? ""} onChange={(event) => setPayload({ ...payload, construction: { ...payload.construction, crew: event.target.value || undefined } })}/></Field><Field label="作业人数"><Input type="number" min="0" value={payload.construction.worker_count ?? ""} onChange={(event) => setPayload({ ...payload, construction: { ...payload.construction, worker_count: event.target.value ? Number(event.target.value) : undefined } })}/></Field></div>
        <Field label="备注"><Textarea value={payload.notes ?? ""} onChange={(event) => setPayload({ ...payload, notes: event.target.value || undefined })}/></Field><Field label="缺失字段（每行一项）"><Textarea value={payload.missing_fields.join("\n")} onChange={(event) => setPayload({ ...payload, missing_fields: event.target.value.split("\n").filter(Boolean) })}/></Field><Field label="歧义与警告（每行一项）"><Textarea value={payload.warnings.join("\n")} onChange={(event) => setPayload({ ...payload, warnings: event.target.value.split("\n").filter(Boolean) })}/></Field>
      </Card>
      <Card className="mb-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">识别到的问题</h2><p className="mt-1 text-xs text-slate-500">默认不创建待办，必须逐项主动勾选并补齐字段</p></div><Button size="sm" variant="secondary" onClick={() => setPayload({ ...payload, issues: [...payload.issues, { description: "", category: "other", evidence_quote: "", needs_confirmation: true }] })}><Plus size={15}/>添加</Button></div>{payload.issues.length === 0 && <Notice>没有识别出问题，仍可创建普通现场记录。</Notice>}{payload.issues.map((issue, index) => <IssueEditor key={index} index={index} issue={issue} members={members} choice={choices[index]} onIssue={(changes) => updateIssue(index, changes)} onChoice={(choice) => setChoices({ ...choices, [index]: choice })} onRemove={() => setPayload({ ...payload, issues: payload.issues.filter((_, itemIndex) => itemIndex !== index) })}/>)}</Card>
      <Card className="mb-4"><Field label="字段来源证据（JSON，可修订）"><Textarea className="min-h-48 font-mono text-sm" value={evidenceJson} onChange={(event) => setEvidenceJson(event.target.value)}/></Field></Card>
      <Card className="mb-4 space-y-4"><h2 className="font-bold">4. 正式记录信息</h2><Field label="记录类别"><Select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="确认后的现场描述"><Textarea value={description} onChange={(event) => setDescription(event.target.value)}/></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="楼栋"><Select value={building} onChange={(event) => { setBuilding(event.target.value); setFloor(""); setLocationId(0); }}><option value="">请选择</option>{buildings.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="楼层"><Select value={floor} onChange={(event) => { setFloor(event.target.value); setLocationId(0); }} disabled={!building}><option value="">请选择</option>{floors.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="区域"><Select value={locationId} onChange={(event) => setLocationId(Number(event.target.value))} disabled={!floor}><option value="0">请选择</option>{zones.map((item) => <option key={item.id} value={item.id}>{item.zone}</option>)}</Select></Field></div></Card>
      <Notice>最终确认将以单个数据库事务创建正式记录和您明确勾选的待办；重复点击不会重复创建。</Notice><Button size="lg" className="mt-4 w-full" onClick={confirm} disabled={busy === "confirm"}>{busy === "confirm" ? <><Loader2 className="animate-spin"/>正在确认…</> : <><CheckCircle2/>最终确认并创建记录</>}</Button>
    </>}
  </div>;
}

function IssueEditor({ index, issue, members, choice, onIssue, onChoice, onRemove }: { index: number; issue: EventIssue; members: User[]; choice?: TaskChoice; onIssue: (value: Partial<EventIssue>) => void; onChoice: (value: TaskChoice) => void; onRemove: () => void }) {
  const current = choice ?? { create_task: false, title: issue.description.slice(0, 120), assignee_id: issue.candidate_project_member_id ?? 0, due_at: issue.proposed_deadline ? localDateTime(issue.proposed_deadline) : "" };
  return <div className="mt-4 space-y-3 rounded-xl border border-amber-200 bg-amber-50/40 p-3"><div className="flex justify-between"><strong>问题 {index + 1}</strong><button className="min-h-10 text-red-700" onClick={onRemove} aria-label={`删除问题 ${index + 1}`}><Trash2 size={17}/></button></div><Field label="问题描述"><Textarea value={issue.description} onChange={(event) => onIssue({ description: event.target.value })}/></Field><Field label="分类（仅草稿，不代表正式安全结论）"><Select value={issue.category} onChange={(event) => onIssue({ category: event.target.value as EventIssue["category"] })}><option value="safety">安全</option><option value="quality">质量</option><option value="civilized_construction">文明施工</option><option value="other">其他</option></Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="责任人原话"><Input value={issue.responsible_person_text ?? ""} onChange={(event) => onIssue({ responsible_person_text: event.target.value || undefined })}/></Field><Field label="候选项目成员"><Select value={issue.candidate_project_member_id ?? 0} onChange={(event) => onIssue({ candidate_project_member_id: Number(event.target.value) || undefined })}><option value="0">需人工选择</option>{members.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.role}</option>)}</Select></Field><Field label="截止时间原话"><Input value={issue.deadline_text ?? ""} onChange={(event) => onIssue({ deadline_text: event.target.value || undefined })}/></Field><Field label="建议截止时间"><Input type="datetime-local" value={issue.proposed_deadline ? localDateTime(issue.proposed_deadline) : ""} onChange={(event) => onIssue({ proposed_deadline: event.target.value ? new Date(event.target.value).toISOString() : undefined })}/></Field></div><Field label="问题证据原文"><Textarea value={issue.evidence_quote} onChange={(event) => onIssue({ evidence_quote: event.target.value })}/></Field>
    <label className="flex min-h-12 items-center gap-3 rounded-xl border border-site-300 bg-white px-3 font-semibold"><input type="checkbox" className="size-5" checked={current.create_task} onChange={(event) => onChoice({ ...current, create_task: event.target.checked })}/>确认对此问题创建待办</label>{current.create_task && <div className="space-y-3 rounded-xl bg-white p-3"><Field label="待办标题"><Input value={current.title} onChange={(event) => onChoice({ ...current, title: event.target.value })}/></Field><Field label="责任人"><Select value={current.assignee_id} onChange={(event) => onChoice({ ...current, assignee_id: Number(event.target.value) })}><option value="0">请选择项目成员</option>{members.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.role}</option>)}</Select></Field><Field label="截止时间"><Input type="datetime-local" value={current.due_at} onChange={(event) => onChoice({ ...current, due_at: event.target.value })}/></Field></div>}</div>;
}
