"use client";
import Link from "next/link";
import { ArrowLeft, AudioLines, Camera, CheckCircle2, Crosshair, ExternalLink, FileCheck2, Fingerprint, MapPin, Plus, Trash2, UserRound } from "lucide-react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Button, Card, Notice } from "@/components/ui";
import { SiteEventCard } from "@/components/site-event-card";
import { useWorkspace } from "@/components/workspace";
import { api, ApiError, photoUrl } from "@/lib/api";
import type { EventPayload, RecordItem, TaskItem, VoiceEvidence } from "@/lib/types";
import { formatDate } from "@/lib/utils";

export default function RecordDetailPage() {
  const { project } = useWorkspace(); const { id } = useParams<{ id: string }>(); const router = useRouter(); const search = useSearchParams(); const [record, setRecord] = useState<RecordItem>(); const [tasks, setTasks] = useState<TaskItem[]>([]); const [voice, setVoice] = useState<VoiceEvidence>(); const [error, setError] = useState(""); const [confirming, setConfirming] = useState(false);
  const load = () => { Promise.all([api<RecordItem>(`/api/records/${id}`), api<TaskItem[]>(`/api/tasks?project_id=${project.id}`)]).then(async ([recordData, taskData]) => { setRecord(recordData); setTasks(taskData.filter((task) => task.source_record_id === recordData.id)); if (recordData.source_type === "VOICE_AI") setVoice(await api<VoiceEvidence>(`/api/records/${id}/voice-evidence`)); }).catch((e: ApiError) => setError(e.message)); };
  useEffect(load, [id, project.id]);
  const deletePhoto = async (photoId: number) => { try { await api(`/api/photos/${photoId}`, { method: "DELETE" }); load(); } catch (e) { setError((e as ApiError).message); } };
  const deleteRecord = async () => { try { await api(`/api/records/${id}`, { method: "DELETE" }); router.replace("/records"); } catch (e) { setError((e as ApiError).message); } };
  if (error && !record) return <Notice tone="error">{error}</Notice>;
  if (!record) return <div className="py-12 text-center text-slate-500">正在加载记录详情…</div>;
  return <div className="mx-auto max-w-3xl"><Link href="/records" className="mb-4 inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-site-700"><ArrowLeft size={17}/>返回现场记录</Link>{search.get("created") && <div className="mb-4"><Notice tone="success">现场记录已保存</Notice></div>}{error && <div className="mb-4"><Notice tone="error">{error}</Notice></div>}
    <div className="mb-5 flex items-start justify-between gap-3"><div><span className="rounded-full bg-site-50 px-3 py-1 text-xs font-bold text-site-800">{record.category}</span><p className="mt-3 text-xs font-bold tracking-widest text-site-600">FIELD EVIDENCE</p><h1 className="mt-1 text-3xl font-black text-ink-900">现场事实记录 #{record.id}</h1><p className="mt-1 text-sm text-slate-500">原始证据、AI 提取与人工确认分层留存</p></div><Button asChild size="sm"><Link href={`/tasks/new?source_record_id=${record.id}`}><Plus size={17}/>创建待办</Link></Button></div>
    <Card className="mb-4 overflow-hidden bg-ink-900 p-0 text-white"><div className="grid grid-cols-3 divide-x divide-white/10">{[[Camera,"01 现场证据",`${record.photos.length} 张照片`],[Fingerprint,"02 事实结构化",record.structured_event ? "已形成事实卡" : "等待提取"],[CheckCircle2,"03 人工确认",record.structured_event ? "全程可追溯" : "待人工核对"]].map(([Icon,title,sub]) => <div key={title as string} className="px-3 py-4 text-center"><Icon className="mx-auto text-gold-300" size={19}/><strong className="mt-2 block text-xs sm:text-sm">{title as string}</strong><span className="mt-1 block text-[10px] text-white/45 sm:text-xs">{sub as string}</span></div>)}</div></Card>
    <Card className="mb-4 border-l-4 border-l-site-600"><h2 className="mb-3 flex items-center gap-2 font-bold"><FileCheck2 size={18} className="text-site-600"/>原始现场描述</h2><p className="whitespace-pre-wrap leading-7 text-slate-800">{record.description}</p></Card>
    {voice && <VoiceEvidenceCard voice={voice} structured={record.structured_event}/>}
    <SiteEventCard record={record}/>
    <div className="mb-4 grid gap-4 sm:grid-cols-2"><Card><h2 className="mb-3 font-bold">人员与项目</h2><Info icon={UserRound} label="记录人" value={`${record.recorder.name} · ${record.recorder.role}`}/><Info label="单位" value={record.recorder.organization}/><Info label="所属项目" value={record.project.name}/><Info label="记录时间" value={new Date(record.occurred_at).toLocaleString("zh-CN")}/></Card><Card><h2 className="mb-3 font-bold">位置与 GPS</h2><Info icon={MapPin} label="施工位置" value={`${record.location.building} · ${record.location.floor} · ${record.location.zone}`}/>{record.gps_status === "success" ? <><Info icon={Crosshair} label="坐标" value={`${record.latitude?.toFixed(6)}, ${record.longitude?.toFixed(6)}`}/><Info label="精度" value={`±${Math.round(record.gps_accuracy ?? 0)} 米`}/><Info label="定位时间" value={record.gps_captured_at ? new Date(record.gps_captured_at).toLocaleString("zh-CN") : "—"}/></> : <Notice>未获取定位（{gpsLabel(record.gps_status)}）</Notice>}</Card></div>
    <Card className="mb-4"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><Camera size={18}/>现场照片</h2><span className="text-sm text-slate-500">{record.photos.length} 张</span></div>{record.photos.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{record.photos.map((photo, index) => <div key={photo.id}><a href={photoUrl(photo.content_url)} target="_blank" rel="noreferrer" className="group relative block aspect-square overflow-hidden rounded-xl bg-slate-100"><img src={photoUrl(photo.content_url)} alt={`现场照片 ${index + 1}`} className="size-full object-cover"/><span className="absolute bottom-2 right-2 grid size-8 place-items-center rounded-full bg-black/60 text-white"><ExternalLink size={15}/></span></a><button onClick={() => deletePhoto(photo.id)} className="mt-1 flex min-h-10 w-full items-center justify-center gap-1 text-xs font-semibold text-red-700"><Trash2 size={14}/>删除照片</button></div>)}</div> : <div className="py-6 text-center text-sm text-slate-500">未上传现场照片</div>}</Card>
    <Card className="mb-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">关联待办</h2><Button asChild size="sm" variant="secondary"><Link href={`/tasks/new?source_record_id=${record.id}`}><Plus size={15}/>新建</Link></Button></div>{tasks.length ? <div className="divide-y divide-slate-100">{tasks.map((task) => <Link key={task.id} href={`/tasks/${task.id}`} className="flex min-h-16 items-center justify-between gap-3 py-2"><div><p className="font-semibold">{task.title}</p><p className="text-xs text-slate-500">{task.assignee.name} · {formatDate(task.due_at)}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{task.status}</span></Link>)}</div> : <p className="py-5 text-center text-sm text-slate-500">暂无关联待办</p>}</Card>
    <Card className="border-red-200"><h2 className="font-bold text-red-800">删除记录</h2><p className="mt-1 text-sm text-slate-600">删除后，关联照片将同步清理，来源待办会保留但不再关联此记录。</p>{confirming ? <div className="mt-3 flex gap-2"><Button variant="danger" onClick={deleteRecord}>确认删除</Button><Button variant="secondary" onClick={() => setConfirming(false)}>取消</Button></div> : <Button className="mt-3" variant="danger" onClick={() => setConfirming(true)}><Trash2 size={17}/>删除现场记录</Button>}</Card>
  </div>;
}
function Info({ icon: Icon, label, value }: { icon?: typeof MapPin; label: string; value: string }) { return <div className="mb-3 flex gap-2 text-sm">{Icon && <Icon className="mt-0.5 shrink-0 text-site-700" size={16}/>}<span className="w-16 shrink-0 text-slate-500">{label}</span><span className="font-medium text-slate-800">{value}</span></div>; }
function gpsLabel(status: string) { return ({ not_requested: "未请求", denied: "权限被拒绝", timeout: "请求超时", unsupported: "浏览器不支持", failed: "定位失败" } as Record<string,string>)[status] ?? "未成功"; }
function VoiceEvidenceCard({ voice, structured }: { voice: VoiceEvidence; structured?: string }) { const event = structured ? JSON.parse(structured) as EventPayload : undefined; return <Card className="mb-4 space-y-4"><h2 className="flex items-center gap-2 font-bold"><AudioLines size={18}/>语音与 AI 证据链</h2>{voice.job.original_audio && <audio className="w-full" controls src={photoUrl(voice.job.original_audio.content_url)}/>}<div><h3 className="text-sm font-semibold">ASR 原始文本</h3><p className="mt-1 whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-sm">{voice.job.raw_transcript}</p></div><div><h3 className="text-sm font-semibold">用户修订文本</h3><p className="mt-1 whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-sm">{voice.job.edited_transcript || "未修订"}</p></div>{event && <div><h3 className="text-sm font-semibold">确认后的结构化 Event</h3><dl className="mt-2 grid gap-2 text-sm"><div><dt className="text-slate-500">类型</dt><dd className="font-semibold">{event.event_type}</dd></div>{event.construction.activity && <div><dt className="text-slate-500">施工活动</dt><dd>{event.construction.activity}</dd></div>}{event.construction.progress_percent != null && <div><dt className="text-slate-500">进度</dt><dd>{event.construction.progress_percent}%</dd></div>}</dl>{event.issues.map((issue, index) => <div key={index} className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3"><strong>问题 {index + 1}：{issue.description}</strong><p className="mt-1 text-xs text-slate-600">证据原文：{issue.evidence_quote}</p></div>)}<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-site-700">查看字段来源证据</summary><pre className="mt-2 overflow-auto rounded-xl bg-slate-900 p-3 text-xs text-white">{JSON.stringify(event.field_evidence, null, 2)}</pre></details></div>}</Card>; }
