"use client";

import Link from "next/link";
import { ArrowLeft, Camera, CheckCircle2, CircleDot, ExternalLink, Play, RotateCcw, ShieldCheck, XCircle } from "lucide-react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { useWorkspace } from "@/components/workspace";
import { Button, Card, Field, Notice, Textarea } from "@/components/ui";
import { api, ApiError, photoUrl } from "@/lib/api";
import type { TaskItem, TaskWorkflow } from "@/lib/types";

const labels: Record<string,string> = { OPEN: "待处理", IN_PROGRESS: "整改中", WAITING_REVIEW: "待复核", DONE: "已闭环", CANCELLED: "已取消", 待处理: "待处理", 处理中: "处理中", 已完成: "已完成", 已取消: "已取消" };

export default function TaskDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const search = useSearchParams(); const { user } = useWorkspace();
  const [task, setTask] = useState<TaskItem>(); const [workflow, setWorkflow] = useState<TaskWorkflow>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [note, setNote] = useState(""); const [reason, setReason] = useState(""); const files = useRef<HTMLInputElement>(null);
  const load = useCallback(() => Promise.all([api<TaskItem>(`/api/tasks/${id}`), api<TaskWorkflow>(`/api/tasks/${id}/workflow`)]).then(([item, flow]) => { setTask(item); setWorkflow(flow); }).catch((e: ApiError) => setError(e.message)), [id]);
  useEffect(() => { void load(); }, [load]);
  const act = async (path: string, body?: unknown) => { setBusy(true); setError(""); try { await api(`/api/tasks/${id}/${path}`, { method: "POST", body: body ? JSON.stringify(body) : undefined }); setReason(""); load(); } catch (e) { setError((e as ApiError).message); } finally { setBusy(false); } };
  const submit = async () => { const selected = Array.from(files.current?.files ?? []); const body = new FormData(); body.append("note", note); selected.forEach((file) => body.append("files", file)); setBusy(true); try { await api(`/api/tasks/${id}/rectification-submissions`, { method: "POST", body }); setNote(""); if (files.current) files.current.value = ""; load(); } catch (e) { setError((e as ApiError).message); } finally { setBusy(false); } };
  const remove = async () => { try { await api(`/api/tasks/${id}`, { method: "DELETE" }); router.replace("/tasks"); } catch (e) { setError((e as ApiError).message); } };
  if (!task || !workflow) return <div>{error ? <Notice tone="error">{error}</Notice> : <p className="py-12 text-center text-slate-500">正在读取任务详情…</p>}</div>;
  const rectification = workflow.kind === "RECTIFICATION";
  return <div className="mx-auto max-w-3xl"><Link href="/tasks" className="mb-4 inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-site-700"><ArrowLeft size={17}/>返回待办中心</Link>{search.get("created") && <div className="mb-4"><Notice tone="success">{rectification ? "整改任务已创建，引用和人工确认内容已冻结。" : "待办已创建"}</Notice></div>}{error && <div className="mb-4"><Notice tone="error">{error}</Notice></div>}
    <div className="mb-5"><Status value={workflow.status}/><p className="mt-3 text-xs font-bold tracking-widest text-site-600">{rectification ? "RECTIFICATION WORKFLOW" : "GENERAL TASK"}</p><h1 className="mt-1 break-words text-3xl font-black text-ink-900">{workflow.title}</h1></div>
    {rectification && <Card className="mb-4 bg-ink-900 p-4 text-white"><div className="grid grid-cols-4">{[["OPEN","发现问题"],["IN_PROGRESS","整改中"],["WAITING_REVIEW","待复核"],["DONE","完成闭环"]].map(([status,label], index) => { const order = ["OPEN","IN_PROGRESS","WAITING_REVIEW","DONE"]; const active = order.indexOf(workflow.status) >= index || workflow.status === "DONE"; return <div key={status} className="relative text-center">{index < 3 && <span className={`absolute left-[62%] top-4 h-px w-[76%] ${active ? "bg-site-500" : "bg-white/15"}`}/>}<span className={`relative mx-auto grid size-8 place-items-center rounded-full ${active ? "bg-site-600" : "bg-white/10 text-white/30"}`}>{active ? <CheckCircle2 size={16}/> : <CircleDot size={16}/>}</span><span className="mt-2 block text-[10px] font-bold sm:text-xs">{label}</span></div>; })}</div></Card>}
    <Card className="mb-4"><h2 className="font-bold">任务要求</h2><p className="mt-2 whitespace-pre-wrap break-words leading-7">{workflow.description}</p><dl className="mt-4 grid gap-2 text-sm"><Detail label="责任人" value={`${task.assignee.name} · ${task.assignee.role}`}/><Detail label="创建人" value={`${task.creator.name} · ${task.creator.role}`}/><Detail label="截止时间" value={new Date(task.due_at).toLocaleString("zh-CN")}/></dl>{workflow.source_issue_id && <Link href={`/issues/${workflow.source_issue_id}`} className="mt-3 inline-flex min-h-11 items-center gap-1 font-semibold text-site-700"><ExternalLink size={15}/>查看来源问题和冻结引用</Link>}</Card>
    {workflow.status === "OPEN" && workflow.assignee_id === user.id && <Button className="mb-4 w-full" onClick={() => act("start")} disabled={busy}><Play size={17}/>开始任务</Button>}
    {rectification && workflow.status === "IN_PROGRESS" && workflow.assignee_id === user.id && <Card className="mb-4 space-y-3"><h2 className="flex items-center gap-2 font-bold"><Camera size={18}/>提交本轮整改证据</h2><Notice>必须提交整改说明和 1–9 张真实 JPEG、PNG 或 WebP 照片；每张不超过 10MB。</Notice><Field label="整改说明"><Textarea value={note} onChange={(e) => setNote(e.target.value)}/></Field><input ref={files} className="block min-h-12 w-full max-w-full rounded-xl border border-slate-300 p-2 text-sm" type="file" accept="image/jpeg,image/png,image/webp" multiple/><Button className="w-full" disabled={busy || !note.trim()} onClick={submit}>提交复核</Button></Card>}
    {rectification && workflow.status === "WAITING_REVIEW" && user.id !== workflow.assignee_id && (user.id === workflow.creator_id || user.role === "安全员") && <Card className="mb-4 space-y-3"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck size={18}/>复核当前轮次</h2><Field label="复核意见（退回时必填）"><Textarea value={reason} onChange={(e) => setReason(e.target.value)}/></Field><div className="grid grid-cols-2 gap-2"><Button onClick={() => act("reviews", { decision: "APPROVE", reason: reason || null })} disabled={busy}><CheckCircle2 size={16}/>通过</Button><Button variant="danger" onClick={() => act("reviews", { decision: "REJECT", reason })} disabled={busy || !reason.trim()}><RotateCcw size={16}/>退回</Button></div></Card>}
    {rectification && <section className="mb-4"><h2 className="mb-3 text-lg font-bold">整改证据与复核时间线</h2>{workflow.submissions.length === 0 ? <Card className="text-center text-sm text-slate-500">尚未提交整改证据</Card> : <div className="space-y-4">{workflow.submissions.map((submission) => <Card key={submission.id}><div className="flex items-center justify-between"><h3 className="font-bold">第 {submission.round_number} 轮整改</h3><span className="text-xs text-slate-500">{new Date(submission.created_at).toLocaleString("zh-CN")}</span></div><p className="mt-3 whitespace-pre-wrap break-words text-sm">{submission.note}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{submission.photos.map((photo) => <a key={photo.id} href={photoUrl(photo.content_url)} target="_blank" rel="noreferrer" className="aspect-square overflow-hidden rounded-xl bg-slate-100"><img className="size-full object-cover" src={photoUrl(photo.content_url)} alt={photo.original_name}/></a>)}</div>{submission.review ? <div className={`mt-3 rounded-xl p-3 text-sm ${submission.review.decision === "APPROVE" ? "bg-emerald-50 text-emerald-900" : "bg-red-50 text-red-900"}`}><strong>{submission.review.decision === "APPROVE" ? "复核通过" : "复核退回"}</strong>{submission.review.reason && <p className="mt-1">{submission.review.reason}</p>}</div> : <p className="mt-3 rounded-xl bg-violet-50 p-3 text-sm text-violet-800">等待复核</p>}</Card>)}</div>}</section>}
    {!rectification && <Card className="mb-4"><h2 className="font-bold">普通待办操作</h2><div className="mt-3 flex flex-wrap gap-2">{workflow.status === "OPEN" && workflow.assignee_id === user.id && <Button onClick={() => act("start")}>开始</Button>}{!["DONE", "CANCELLED"].includes(workflow.status) && workflow.assignee_id === user.id && <Button onClick={() => act("complete")}>完成</Button>}<Button variant="danger" onClick={remove}>删除普通待办</Button></div></Card>}
    {!(["DONE", "CANCELLED"].includes(workflow.status)) && <Card><h2 className="font-bold">取消任务</h2><Field label="取消原因"><Textarea className="mt-3" value={reason} onChange={(e) => setReason(e.target.value)}/></Field><Button className="mt-3" variant="danger" disabled={!reason.trim() || busy} onClick={() => act("cancel", { reason })}><XCircle size={16}/>取消任务</Button></Card>}
  </div>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex gap-2"><dt className="w-20 shrink-0 text-slate-500">{label}</dt><dd className="break-words font-semibold">{value}</dd></div>; }
function Status({ value }: { value: string }) { return <span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{labels[value] ?? value}</span>; }
